# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(14)-高级Opengl-立方体贴图' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(14)-高级Opengl-立方体贴图
  pod 'OpenGLUtils', :path => '../openGL'
  pod 'OpenGLBase', :path => '../openGLBase'
  target 'OpenGLZeroStudyDemo(14)-高级Opengl-立方体贴图Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(14)-高级Opengl-立方体贴图UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

