# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(18)-高级光照之阴影' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(18)-高级光照之阴影
  pod 'OpenGLUtils', :path => '../openGL'
  pod 'OpenGLBase', :path => '../openGLBase'
  pod 'openGLResource', :path => '../openGLResource'
  target 'OpenGLZeroStudyDemo(18)-高级光照之阴影Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(18)-高级光照之阴影UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
