# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(13)-高级Opengl-帧缓冲' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(13)-高级Opengl-帧缓冲

  pod 'OpenGLUtils', :path => '../openGL'
  pod 'OpenGLBase', :path => '../openGLBase'
  target 'OpenGLZeroStudyDemo(13)-高级Opengl-帧缓冲Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(13)-高级Opengl-帧缓冲UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
