# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(6)-粒子效果' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(6)-粒子效果
  pod 'OpenGLUtils', :path => '../openGL'
  target 'OpenGLZeroStudyDemo(6)-粒子效果Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(6)-粒子效果UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
