# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(4)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(4)

  target 'OpenGLZeroStudyDemo(4)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(4)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
