# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(9)-高级Opengl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(9)-高级Opengl
 pod 'OpenGLUtils', :path => '../openGL'
 pod 'OpenGLBase', :path => '../openGLBase'

  target 'OpenGLZeroStudyDemo(9)-高级OpenglTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(9)-高级OpenglUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
