# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(17)-高级光照之高级光照' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(17)-高级光照之高级光照
  pod 'OpenGLUtils', :path => '../openGL'
  pod 'OpenGLBase', :path => '../openGLBase'
  target 'OpenGLZeroStudyDemo(17)-高级光照之高级光照Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(17)-高级光照之高级光照UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
