# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OpenGLZeroStudyDemo(11)-高级Opengl-混合' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGLZeroStudyDemo(11)-高级Opengl-混合
  pod 'OpenGLUtils', :path => '../openGL'
  pod 'OpenGLBase', :path => '../openGLBase'
  target 'OpenGLZeroStudyDemo(11)-高级Opengl-混合Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLZeroStudyDemo(11)-高级Opengl-混合UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
